name: Update Product Search
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to update product
        run: |
          run: |
          curl --request GET \
            --url '${{ secrets.SITE_URL }}/api/algolia' \
            --header 'x-api-secret: ${{ secrets.API_SECRET }}'